# Generated by Django 4.1.6 on 2023-12-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_equipo', models.TextField(max_length=50)),
                ('telefono_cliente', models.IntegerField(max_length=10)),
                ('tipo_equipo', models.CharField(choices=[('E', 'Escritorio-CPU'), ('P', 'Portatil'), ('A', 'Alo'), ('I', 'Impresora'), ('M', 'Multifuncional'), ('T', 'Tablet')], default='P', max_length=1)),
                ('marca_equipo', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=15)),
                ('accesorios_equipo', models.TextField(max_length=100)),
                ('contraseña_equipo', models.CharField(max_length=30)),
                ('sistema_operativo', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('cotizacion', models.FloatField(max_length=5)),
                ('tipo_servicio', models.CharField(max_length=20)),
                ('falla_equipo', models.CharField(max_length=200)),
                ('indicaciones_adicionales', models.CharField(max_length=70)),
                ('servicio_realizado', models.CharField(max_length=150)),
                ('notas_finales', models.CharField(max_length=150)),
                ('encargado', models.CharField(max_length=50)),
                ('partes', models.CharField(max_length=70)),
                ('fecha_entrega', models.DateField()),
                ('costo_final', models.FloatField(max_length=5.2)),
                ('observaciones_notas', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.equipo')),
            ],
        ),
    ]
