# Generated by Django 4.1.6 on 2023-12-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_equipo_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='serial_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
