# Generated by Django 4.1.6 on 2023-12-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_equipo_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
