# Generated by Django 4.1.6 on 2023-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_ordenservicio_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_final',
            field=models.FloatField(max_length=5.2, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='encargado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='notas_finales',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='observaciones_notas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='partes',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='servicio_realizado',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
