# Generated by Django 4.1.6 on 2023-12-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_ordenservicio_costo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='accesorios_equipo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='contraseña_equipo',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca_equipo',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo_equipo',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial_number',
            field=models.TextField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.TextField(choices=[('E', 'Escritorio-CPU'), ('P', 'Portatil'), ('A', 'AIO'), ('I', 'Impresora'), ('M', 'Multifuncional'), ('T', 'Tablet')], default='P', max_length=1),
        ),
    ]
