# Generated by Django 4.1.6 on 2023-12-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_equipo_telefono_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
